#ifndef _INSTRUC_H
#define _INSTRUC_H

/*
	Por la mitad de la enumeraci¢n se asignan valores distintos a los de la
	secuencia normal. Esto se hace para que no haya conflictos con los
	valores en el c¢digo ASCII de los operadores '+', '-', etc.
*/
enum { EMPUJA, CARGA, ALMACENA, SALTASBR, RETSBR, SALTAFALSO, SALTA,
	   C_MENOSU, C_NOT, C_AND, C_OR, C_MAY, C_MEN, C_MAI, C_MEI, C_EQU,
	   C_NEQ, C_ESTA, C_ESTAMAY, C_ESTAMEN, C_PRESENTE, C_PUESTO, C_LLEVADO,
	   C_ESTAEN, C_VERB1, C_NOMB1, C_ADJET1, C_ADVERB, C_PREPOS, C_NOMB2,
	   C_ADJET2, C_ACABAR, C_AUSENTE, C_LOCAL, C_OBJETO, C_ANALIZA,
	   C_ALEATORIO, C_PRIMERO, C_SIGUIENTE, C_PESO = 50, C_CONTENEDOR,
	   C_ROPA, C_POSX, C_POSY, C_CAMINAR, A_COGER, A_DEJAR, A_PONER,
	   A_QUITAR, A_CREAR, A_DESTRUIR, A_ACABAR, A_TURNOS, A_HECHO,
	   A_NO_HECHO, A_COLOCAR, A_INTERCAMBIAR, A_METER, A_SACAR, A_AUTOC,
	   A_AUTOD, A_AUTOP, A_AUTOQ, A_AUTOM, A_AUTOS, A_LISTAOBJ, A_LISTADE,
	   A_INVEN, A_MENS, A_MENSIS, A_TECLA, A_PAUSA, A_DESCRIBE, A_MUEVE,
	   A_IMPRIME, A_DIAG, A_SALVAR, A_CARGAR, A_BORRAR, A_SALIDAS, A_CURSOR,
	   A_SALTOLINEA, A_IMAGEN, A_IMAGEN2, A_SONIDO, A_SONIDO2, A_SILENCIO,
	   C_MODULO, A_VENTANA, C_OBJETO_DEFECTO, A_COLOR, A_FONDO,
	   A_LISTACONT, C_DIRECC1, A_FUENTE };

#endif
